Massive improvements to install script

diff --git a/universalinstall b/universalinstall
--- a/universalinstall
+++ b/universalinstall
@@ -1,41 +1,61 @@
 #!/bin/bash
 
-echo "[ ] Checking for brew..." \
-    && (brew --version > /dev/null \
-        && echo "[+] brew already installed.") \
-    || (echo "  [ ] Installing brew..." \
-        && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
-        && echo "  [+] Installing brew succeeded." \
-        || exit "  [-] Installing brew failed!")
+uinstall () {
+    name=$1
+    check_command=$2
+    install_command=$3
 
-echo "[ ] Checking for brew-python2..." \
-    && ([[ $(which python2) == /usr/local/bin/* ]] \
-        && echo "[+] brew-python2 already installed.") \
-    || (echo "  [ ] Installing brew-python2..." \
-        && brew install python2 \
-        && echo "  [+] Installing brew-python2 succeeded." \
-        || exit "  [-] Installing brew-python2 failed!")
+    # check for install
+    echo "[ ] Checking for $name...  ($check_command)"
+    if eval "$check_command &>/dev/null"; then
+        echo "[+] $name already installed."
+        return 0
+    else
+        echo "  [-] $name is not installed."
+    fi
 
-echo "[ ] Checking for brew-python3..." \
-    && ([[ $(which python3) == /usr/local/bin/* ]] \
-        && echo "[+] brew-python3 already installed.") \
-    || (echo "  [ ] Installing brew-python3..." \
-        && brew install python3 \
-        && echo "  [+] Installing brew-python3 succeeded." \
-        || exit "  [-] Installing brew-python3 failed!")
+    # try to install
+    echo "  [ ] Installing $name... ($install_command)"
+    if eval "$install_command &>/dev/null"; then
+        echo "  [+] Installing $name succeeded."
+    else
+        echo "  [!] Installing $name failed!"
+        exit 1
+    fi
+}
 
-echo "[ ] Checking for pip2-virtualenv..." \
-    && (pip2 freeze | grep "virtualenv" > /dev/null \
-        && echo "[+] pip2-virtualenv already installed.") \
-    || (echo "  [ ] Installing pip2-virtualenv..." \
-        && pip2 install virtualenv \
-        && echo "  [+] Installing pip2-virtualenv succeeded.  Remember to add [alias virtualenv2='virtualenv -p python2'] to your ~/.bash_profile!" \
-        || exit "  [-] Installing pip2-virtualenv failed!")
+# uinstall 'failtest' \
+#     'failtest' \
+#     'failtest'
 
-echo "[ ] Checking for pip3-virtualenv..." \
-    && (pip3 freeze | grep "virtualenv" > /dev/null \
-        && echo "[+] pip3-virtualenv already installed.") \
-    || (echo "  [ ] Installing pip3-virtualenv..." \
-        && pip3 install virtualenv \
-        && echo "  [+] Installing pip3-virtualenv succeeded.  Remember to add [alias virtualenv3='virtualenv -p python3'] to your ~/.bash_profile!" \
-        || exit "  [-] Installing pip3-virtualenv failed!")
+# uinstall 'installtest' \
+#     'installtest' \
+#     'sleep 1'
+
+# uinstall 'successtest' \
+#     'sleep 1' \
+#     ''
+
+uinstall 'brew' \
+    'brew --version' \
+    '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
+
+uinstall 'brew-python2' \
+    'which python2 | head -n 1 | grep /usr/local/bin/' \
+    'brew install python2'
+
+uinstall 'brew-python3' \
+    'which python3 | head -n 1 | grep /usr/local/bin/' \
+    'brew install python3'
+
+uinstall 'pip2-virtualenv' \
+    'pip2 freeze | grep "virtualenv"' \
+    'pip2 install virtualenv'
+
+uinstall 'pip3-virtualenv' \
+    'pip3 freeze | grep "virtualenv"' \
+    'pip3 install virtualenv'
+
+uinstall 'pip3-vulture' \
+    'pip3 freeze | grep "vulture"' \
+    'pip3 install vulture'
